### ISSUE TITLE
Web server failure in demo app

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [hashicorp-education/learn-vault-redhat-openshift#1]
Running the tutorial on:

Vault installation to Red Hat OpenShift via Helm
https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-openshift

under OpenShift Local 4.16.7. The webapp container failed to answer requests, no doubt due to the failure of the Ruby Sinatra in the "app" container:

```
2024-09-18 21:00:05 - NoMethodError - undefined method `[]' for nil:NilClass:
	/app/lib/service.rb:51:in `block in <class:ExampleApp>'
	/usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `call'
	/usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:1006:in `route_eval'
	/usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.7/lib/sinatra/base.rb:1035:in `block in process_route'
```
(and so on.)

I realize the problem in is the underlying app container image, where I will try to post this as well. But this does sabotage the demo so I thought you would want to know.

Jeff

**Comment by jwilliams-shadowsoft** [comment]
I found the issue. The text of the tutorial is only written to accommodate the namespace "default", but I was using a different namespace. Once the rolebindings were correct Sinatra seemed to come up and run normally.
